name: flask
services:
  flask:
    restart: unless-stopped
    build:
      context: ./flask
      dockerfile: Dockerfile
    deploy:
      resources:
        reservations:
          cpus: "1.0"
          memory: 512M
    ports:
      - mode: ingress
        target: 5000
        published: 5000
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/"]
      interval: 30s
      retries: 3
      start_period: 30s
      timeout: 10s